all: gcc

prepare:
	mkdir -p Output

gcc: prepare
	gcc LuaShell.c LuaBins/liblua55.a -o Output/luaic -I./LuaIncludes -static -lm

mingw: prepare
	x86_64-w64-mingw32-gcc LuaShell.c LuaBins/liblua55.a -o Output/luaic.exe -I./LuaIncludes -static -lm

tcc: prepare
	tcc LuaShell.c LuaBins/liblua55.a -o Output/luaic -I./LuaIncludes -static -lm

clean:
	rm -rf Output/
